[package]
name = "actix-rs"
version = "0.1.0"
edition = "2021"

#[[bin]]
#name = "actix-rs"
#path = "src/main/main.rs"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
env_logger = "0.11.5"
http = "0.2.12"
