
services:
  actix-app:
    container_name: actix-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

networks:
  dev_nk:
    driver: bridge